"""Solar copilot package — re-exports all public names from submodules."""

from solar_platform.services.copilot.models import (
    ASSET_CONTEXT_FIELD_CANDIDATES,
    CAPACITY_FIELD_CANDIDATES,
    DAILY_JSON_DATABASE_PROPERTIES,
    DAILY_JSON_DATABASE_TITLE,
    DATA_SOURCE_MATCH_FIELD_CANDIDATES,
    DEFAULT_CONFIRMED_SOURCE_REGISTRY,
    DEFAULT_DATA_SOURCE_MATCH_UPDATES,
    DEFAULT_PPA_RATE_GBP_MWH,
    DEFAULT_PPA_RATE_SOURCE,
    INVERTER_METER_ALERT_CRITICAL_PCT,
    PAC_DATE_FIELD_CANDIDATES,
    PLATFORM_FIELD_CANDIDATES,
    PPA_RATE_FIELD_CANDIDATES,
    SEVERITY_RANK,
    SOURCE_CREDENTIAL_REPORT_ORDER,
    SOURCE_IDENTIFIER_FIELD_CANDIDATES,
    STARK_DAILY_DATABASE_TITLE,
    STARK_FUSION_VARIANCE_THRESHOLD_PCT,
    SUPPORTED_SOURCES,
    TARGET_PR_ASSUMPTION,
    TRIAGE_DATABASE_PROPERTIES,
    TRIAGE_DATABASE_TITLE,
    CurtailmentFetcher,
    DailyDataChecker,
    MatchResolution,
    SourceCheckResult,
    TriageAssessment,
    ASSET_NAME_FIELD_CANDIDATES,
)
from solar_platform.services.copilot.mapping import (
    _build_evidence_summary,
    _build_finding,
    _build_rich_text_items,
    _canonical_platform,
    _clean_identifier,
    _coerce_date,
    _coerce_float,
    _coerce_platform_tokens,
    _date_property,
    _default_legacy_mapping_path,
    _derive_pac_phase,
    _extract_asset_context,
    _extract_asset_name,
    _extract_capacity_kwp,
    _extract_ppa_rate_gbp_mwh,
    _extract_solis_day_energy_from_payload,
    _get_candidate_and_value,
    _get_value,
    _load_legacy_mapping,
    _normalise_key,
    _number_property,
    _severity_sort_key,
    _text_property,
    _title_property,
)
from solar_platform.services.copilot.triage import (
    _assess_triage_issue,
    _build_email_draft,
    _build_email_subject,
    _build_fallback_email_draft,
)
from solar_platform.services.copilot.curtailment import ExportLimitCurtailmentFetcher
from solar_platform.services.copilot.checkers import (
    AdapterDailyChecker,
    SolarEdgeDailyChecker,
    SolisDailyChecker,
    build_default_checkers,
    _load_solaredge_site_keys,
)
from solar_platform.services.copilot.daylight_metrics import (
    OpenMeteoArchiveIrradianceFetcher,
    OpenMeteoForecastIrradianceFetcher,
    RepositoryDaylightMetricsFetcher,
    _hourly_weather_records_to_half_hourly_df,
)
from solar_platform.services.copilot.audit import (
    AssetRegisterAuditService,
    _load_cached_audit_dataset,
    _resolve_audit_target_date,
    run_asset_register_daily_publish,
    run_asset_register_triage_publish,
    run_asset_register_yesterday_audit,
)

__all__ = [
    # models
    "ASSET_CONTEXT_FIELD_CANDIDATES",
    "ASSET_NAME_FIELD_CANDIDATES",
    "CAPACITY_FIELD_CANDIDATES",
    "DAILY_JSON_DATABASE_PROPERTIES",
    "DAILY_JSON_DATABASE_TITLE",
    "DATA_SOURCE_MATCH_FIELD_CANDIDATES",
    "DEFAULT_CONFIRMED_SOURCE_REGISTRY",
    "DEFAULT_DATA_SOURCE_MATCH_UPDATES",
    "DEFAULT_PPA_RATE_GBP_MWH",
    "DEFAULT_PPA_RATE_SOURCE",
    "INVERTER_METER_ALERT_CRITICAL_PCT",
    "PAC_DATE_FIELD_CANDIDATES",
    "PLATFORM_FIELD_CANDIDATES",
    "PPA_RATE_FIELD_CANDIDATES",
    "SEVERITY_RANK",
    "SOURCE_CREDENTIAL_REPORT_ORDER",
    "SOURCE_IDENTIFIER_FIELD_CANDIDATES",
    "STARK_DAILY_DATABASE_TITLE",
    "STARK_FUSION_VARIANCE_THRESHOLD_PCT",
    "SUPPORTED_SOURCES",
    "TARGET_PR_ASSUMPTION",
    "TRIAGE_DATABASE_PROPERTIES",
    "TRIAGE_DATABASE_TITLE",
    "CurtailmentFetcher",
    "DailyDataChecker",
    "MatchResolution",
    "SourceCheckResult",
    "TriageAssessment",
    # mapping
    "_build_evidence_summary",
    "_build_finding",
    "_build_rich_text_items",
    "_canonical_platform",
    "_clean_identifier",
    "_coerce_date",
    "_coerce_float",
    "_coerce_platform_tokens",
    "_date_property",
    "_default_legacy_mapping_path",
    "_derive_pac_phase",
    "_extract_asset_context",
    "_extract_asset_name",
    "_extract_capacity_kwp",
    "_extract_ppa_rate_gbp_mwh",
    "_extract_solis_day_energy_from_payload",
    "_get_candidate_and_value",
    "_get_value",
    "_load_legacy_mapping",
    "_normalise_key",
    "_number_property",
    "_severity_sort_key",
    "_text_property",
    "_title_property",
    # triage
    "_assess_triage_issue",
    "_build_email_draft",
    "_build_email_subject",
    "_build_fallback_email_draft",
    # curtailment
    "ExportLimitCurtailmentFetcher",
    # checkers
    "AdapterDailyChecker",
    "SolarEdgeDailyChecker",
    "SolisDailyChecker",
    "build_default_checkers",
    "_load_solaredge_site_keys",
    # daylight_metrics
    "OpenMeteoArchiveIrradianceFetcher",
    "OpenMeteoForecastIrradianceFetcher",
    "RepositoryDaylightMetricsFetcher",
    "_hourly_weather_records_to_half_hourly_df",
    # audit
    "AssetRegisterAuditService",
    "_load_cached_audit_dataset",
    "_resolve_audit_target_date",
    "run_asset_register_daily_publish",
    "run_asset_register_triage_publish",
    "run_asset_register_yesterday_audit",
]
